# Chapter 1: NumPy Basics

## What is NumPy?

NumPy (Numerical Python) is a powerful Python library used for:

- Scientific computing
- Data analysis
- Machine learning

It provides a high-performance multidimensional array object called `ndarray`.


## Why NumPy over Python List?

| Feature               | Python List         | NumPy Array      |
|-----------------------|---------------------|------------------|
| Performance           | Slower              | Much faster      |
| Memory Efficiency     | Higher memory usage | Low memory usage |
| Element-wise Ops      | Not supported       | Supported        |


In [1]:
# Importing NumPy
import numpy as np

In [2]:
# Python List Example
list1 = [1, 2, 3]
list2 = [4, 5, 6]

# This will concatenate lists, not add them element-wise
print("List + List:", list1 + list2)

List + List: [1, 2, 3, 4, 5, 6]


In [3]:
# NumPy Array Example
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# This performs element-wise addition
print("Array + Array:", arr1 + arr2)

# Element-wise subtraction
print("Array - Array:", arr2 - arr1)

Array + Array: [5 7 9]
Array - Array: [3 3 3]


In [4]:
# Simulating element-wise addition using zip
added_list = [a + b for a, b in zip(list1, list2)]
print("Element-wise addition for list using zip:", added_list)

Element-wise addition for list using zip: [5, 7, 9]


# Chapter 2: Important NumPy Array Operations and Functions

## 1. Array Creation

In [5]:
print("Basic array from list:", np.array([1, 2, 3]))
print("\n3x4 zeros array:\n", np.zeros((3, 4)))
print("\n2x3 ones array:\n", np.ones((2, 3)))
print("\nEmpty 2x2 array (contains garbage values):\n", np.empty((2, 2)))
print("\n3x3 identity matrix:\n", np.eye(3))

# Sequences and ranges
print("\nArange (0-10 step 2):", np.arange(0, 10, 2))
print("\nLinspace (5 values between 0-1):", np.linspace(0, 1, 5))

# Random arrays
print("\nRandom 3x3 (uniform distribution):\n", np.random.rand(3, 3))
print("\nRandom 3x3 (standard normal):\n", np.random.randn(3, 3))

Basic array from list: [1 2 3]

3x4 zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2x3 ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Empty 2x2 array (contains garbage values):
 [[0. 0.]
 [0. 0.]]

3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Arange (0-10 step 2): [0 2 4 6 8]

Linspace (5 values between 0-1): [0.   0.25 0.5  0.75 1.  ]

Random 3x3 (uniform distribution):
 [[0.25784844 0.88154582 0.23231772]
 [0.6040379  0.92266797 0.51201571]
 [0.42194404 0.76145974 0.24829469]]

Random 3x3 (standard normal):
 [[-1.93476143  0.03722961  0.26269227]
 [ 0.84428109 -0.60267328 -1.18544542]
 [-0.49864061  1.37767263 -0.6244885 ]]


## 2. Array Attributes

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)      # (2, 3)
print("Dimensions:", arr.ndim)  # 2
print("Size:", arr.size)        # 6
print("Data type:", arr.dtype)  # int64 (or float64 if decimals)
print("Transpose:\n", arr.T)    # [[1, 4], [2, 5], [3, 6]]

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64
Transpose:
 [[1 4]
 [2 5]
 [3 6]]


## 3. Array Manipulation

In [7]:
# Reshaping
arr = np.arange(6)
print(arr)
arr = arr.reshape(2, 3)
print("\nReshaped 2x3 array:\n", arr)
print("Flattened:", arr.flatten())
print("Raveled (no copy):", arr.ravel())

[0 1 2 3 4 5]

Reshaped 2x3 array:
 [[0 1 2]
 [3 4 5]]
Flattened: [0 1 2 3 4 5]
Raveled (no copy): [0 1 2 3 4 5]


In [8]:
# Joining/Splitting
a, b = np.array([1, 2]), np.array([3, 4])
print("\nConcatenated:", np.concatenate([a, b]))
print("Vertically stacked:\n", np.vstack([a, b]))


Concatenated: [1 2 3 4]
Vertically stacked:
 [[1 2]
 [3 4]]


## 4. Indexing & Slicing

In [9]:
print("Original array:\n", arr)
print("\nElement at [1,2]:", arr[1, 2])
print("Column slicing:\n", arr[:, 1:3])
print("Boolean indexing (>3):", arr[arr > 3])
print("Fancy indexing:", arr[[0, 1], [1, 2]])  # (0,1) and (1,2)

Original array:
 [[0 1 2]
 [3 4 5]]

Element at [1,2]: 5
Column slicing:
 [[1 2]
 [4 5]]
Boolean indexing (>3): [4 5]
Fancy indexing: [1 5]


## 5. Mathematical Operations

In [10]:
a, b = np.array([1, 2, 3]), np.array([4, 5, 6])

print("Element-wise addition:", a + b)
print("Element-wise sqrt:", np.sqrt(a))

# Aggregation
arr = np.array([[1, 2], [3, 4]])
print("\n2D array:\n", arr)
print("Global sum:", np.sum(arr))
print("Column-wise mean:", np.mean(arr, axis=0))
print("Row-wise max:", arr.max(axis=1))
print("Power:", np.power(a,b))

Element-wise addition: [5 7 9]
Element-wise sqrt: [1.         1.41421356 1.73205081]

2D array:
 [[1 2]
 [3 4]]
Global sum: 10
Column-wise mean: [2. 3.]
Row-wise max: [2 4]
Power: [  1  32 729]


## 6. Advanced Operations

In [11]:
print("Unique values:", np.unique([1, 2, 2, 3, 1]))
print("\nWhere (indices where >2):", np.where(np.array([1, 2, 3, 4]) > 2)) # gives indexes
print("\nClipped values (2-3):", np.clip([1, 2, 3, 4], 2, 3)) #In this case: All values < 1 become 1 All values > 2 become 2

Unique values: [1 2 3]

Where (indices where >2): (array([2, 3]),)

Clipped values (2-3): [2 2 3 3]


## 7. Sorting Operations

In [12]:
arr = np.array([3, 1, 4, 2, 5])
print("Original array:", arr)

# Basic sorting
print("\nSorted array (returns new array):", np.sort(arr))
print("Original array remains unchanged:", arr)

# In-place sorting
arr.sort()
print("\nAfter in-place sort:", arr)

# Sorting with indices
arr = np.array([3, 1, 4, 2, 5])
print("\nIndices of sorted elements:", np.argsort(arr))

Original array: [3 1 4 2 5]

Sorted array (returns new array): [1 2 3 4 5]
Original array remains unchanged: [3 1 4 2 5]

After in-place sort: [1 2 3 4 5]

Indices of sorted elements: [1 3 0 2 4]


## 8. String Operations (for string arrays)

In [13]:
arr = np.array(['apple', 'banana', 'cherry'])

print("Uppercase:", np.char.upper(arr))
print("String length:", np.char.str_len(arr))
print("Replace 'a' with 'X':", np.char.replace(arr, 'a', 'X'))

Uppercase: ['APPLE' 'BANANA' 'CHERRY']
String length: [5 6 6]
Replace 'a' with 'X': ['Xpple' 'bXnXnX' 'cherry']


## 9. Set Operations

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print("Unique values:", np.unique([1, 2, 2, 3]))
print("Intersection:", np.intersect1d(a, b))
print("Union:", np.union1d(a, b))
print("Set difference (a - b):", np.setdiff1d(a, b))

Unique values: [1 2 3]
Intersection: [3 4]
Union: [1 2 3 4 5 6]
Set difference (a - b): [1 2]


## 10. Nan (Missing Data) Handling

In [15]:
arr = np.array([1, 2, np.nan, 4])

print("Array with NaN:", arr)
print("Is NaN?:", np.isnan(arr))
print("Mean ignoring NaN:", np.nanmean(arr))
print("Sum ignoring NaN:", np.nansum(arr))

Array with NaN: [ 1.  2. nan  4.]
Is NaN?: [False False  True False]
Mean ignoring NaN: 2.3333333333333335
Sum ignoring NaN: 7.0


## 11. Linear Algebra Function

In [16]:
import numpy as np

# Vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)  # 1*4 + 2*5 + 3*6 = 32
print("Vector dot product:", dot_product)

# Matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
matrix_product = np.dot(A, B)  # [[1*5+2*7, 1*6+2*8], [3*5+4*7, 3*6+4*8]]
print("Matrix multiplication:\n", matrix_product)

Vector dot product: 32
Matrix multiplication:
 [[19 22]
 [43 50]]


In [17]:
# 3D vectors
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
cross_product = np.cross(x, y)  #[x1, x2, x3] × [y1, y2, y3] = [
    # x2*y3 - x3*y2,   First component
    # x3*y1 - x1*y3,   Second component
    # x1*y2 - x2*y1    Third component]
print("Cross product (x × y):", cross_product)

Cross product (x × y): [-3  6 -3]


## 12. Extra Functions

In [18]:
# convert to list
arr = np.array([[1, 2], [3, 4]])
arr.tolist()

[[1, 2], [3, 4]]

In [19]:
# Original array (int32 by default)
arr = np.array([1, 2, 3, 4])
print("Original dtype:", arr.dtype)  # int32 (or int64 depending on system)

# Convert to float
float_arr = arr.astype(np.float32)
print("\nAs float32:", float_arr)
print("New dtype:", float_arr.dtype)

# Convert to string
str_arr = arr.astype(str)
print("\nAs strings:", str_arr)
print("New dtype:", str_arr.dtype)  # <U11 (Unicode string, max length 11)

# Convert to boolean (0 becomes False, non-zero True)
bool_arr = arr.astype(bool)
print("\nAs boolean:", bool_arr)

Original dtype: int64

As float32: [1. 2. 3. 4.]
New dtype: float32

As strings: ['1' '2' '3' '4']
New dtype: <U21

As boolean: [ True  True  True  True]


**Note:** NumPy Methods (Only Work as arr.method())

In [ ]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])

# 1. Shape Manipulation
arr.reshape(4,)      # New shape (no data copy)
arr.resize(3, 3)     # In-place shape change (may pad zeros)
arr.T                # Transpose shortcut (same as arr.transpose())

# 2. Data Handling
arr.flatten()        # 1D copy (vs np.ravel() which may return view)
arr.sort()           # In-place sort
arr.fill(0)          # Replace all values with 0

# 3. Conversion/Copying
arr.tolist()         # Convert to Python list
arr.copy()           # Deep copy
arr.dump('file.npy') # Save to file (pickle format)

arr.shape      # (2, 3)
arr.ndim  # 2
arr.size        # 6
arr.dtype  # int64 (or float64 if decimals)

dtype('int64')